allowBuilds:
    esbuild: true
    sharp: true
    unrs-resolver: true
onlyBuiltDependencies:
    - esbuild
    - sharp
    - unrs-resolver

catalog:
    vite-plus: latest

peerDependencyRules:
    allowAny:
        - vite
        - vitest
    allowedVersions:
        vite: '*'
        vitest: '*'
